server:
    port: 8088

application:
    userproperties:
        allowedUsers:
            - '224823566'
        replyForUnknownUser:
          type: 'TEXT'
          messages:
           - message: "Мне запрещено разговаривать с незнакомцами"
        incomingRequestChatIdReceiver:
            - '32234234'
            - '32232112'
    cmdproperties:
        storeCommandsSeconds: 100
        ignoreUnknownCmd: true
        unknownCmdMessageTemplate:
          type: 'TEXT'
          messages:
          - message: "Неизвестная команда!"
        syncReplyMapping:
            cmd1:
              type: 'TEXT'
              messages:
                - message: "Sync reply on cmd1"
            cmd21:
              type: 'REPLY_MARKUP'
              messages:
                - message: "Sync reply on cmd21"
            cmd22:
              type: 'REPLY_MARKUP'
              messages:
                - message: "Sync reply 1 on cmd22"
                - message: "Sync reply 2 on cmd22"
              resize: 'true'
            cmd23:
              type: 'REPLY_MARKUP'
              messages:
              - message: "Sync reply 1 on cmd23"
              - message: "Sync reply 2 on cmd23"
              resize: 'true'
              selective: 'true'
            cmd24:
              type: 'REPLY_MARKUP'
              messages:
              - message: "Sync reply 1 on cmd24"
              - message: "Sync reply 2 on cmd24"
              resize: 'true'
              selective: 'true'
              oneTime: 'true'
            cmd25:
              type: 'REPLY_MARKUP'
              messages:
              - message: "Sync reply 1 on cmd25"
              - message: "Sync reply 2 on cmd25"
              - message: "Sync reply 3 on cmd25"
              - message: "Sync reply 3 on cmd25"
              columnsLimit: 2
            cmd26:
              type: 'REPLY_MARKUP'
              messages:
              - message: "Sync reply 1 on cmd26"
              - message: "Sync reply 2 on cmd26"
              - message: "Sync reply 3 on cmd26"
              - message: "Sync reply 3 on cmd26"
              columnsLimit: 6
            cmd31:
              type: 'INLINED_MARKUP'
              messages:
              - message: "Sync reply 1 on cmd31"
                callback: "callback on cmd31 reply1"
              - message: "Sync reply 2 on cmd31"
                callback: "callback on cmd31 reply2"
              - message: "Sync reply 3 on cmd31"
                callback: "callback on cmd31 reply3"
              - message: "Sync reply 3 on cmd31"
                callback: "callback on cmd31 reply4"
              columnsLimit: 2
            cmd32:
              type: 'INLINED_MARKUP'
              messages:
              - message: "Sync reply 1 on cmd32"
                callback: "callback on cmd32 reply1"
              - message: "Sync reply 2 on cmd32"
                callback: "callback on cmd32 reply2"
              - message: "Sync reply 3 on cmd32"
                callback: "callback on cmd32 reply3"
              - message: "Sync reply 3 on cmd32"
                callback: "callback on cmd32 reply4"
        asyncCmdProperties:
            globalTimeoutMs: 3000
            globalTimeoutErrorMessage:
              type: 'TEXT'
              messages:
              - message: "Таймаут операции"
            replyMapping:
                cmd3:
                    replyMessage:
                      type: 'TEXT'
                      messages:
                      - message: "Команда cmd3 исполнена на клиенте"
                    beforeActionReplyMessage:
                      type: 'TEXT'
                      messages:
                      - message: "Команда cmd3 принята в обработку"
                    timeoutMs: 15000
                    timeoutErrorMessage:
                      type: 'TEXT'
                      messages:
                      - message: "Таймаут для cmd3!"
                cmd4:
                    replyMessage:
                      type: 'TEXT'
                      messages:
                      - message: "Команда cmd4 исполнена на клиенте"
                    beforeActionReplyMessage:
                      type: 'TEXT'
                      messages:
                      - message: "Команда cmd4 принята в обработку"
                    timeoutMs: 20000
                    timeoutErrorMessage:
                      type: 'TEXT'
                      messages:
                      - message: "Таймаут для cmd4!"
                cmd5:
                    replyMessage:
                      type: 'TEXT'
                      messages:
                      - message: "Команда cmd5 исполнена на клиенте"
    botproperties:
        connectionTimeoutMs: 3000
        name: 'AlexeyLemberskiy_bot'
        token: '977798690:AAHMv3t-kfQhxM16MpEvdCa39e5NAQgsZB4'