server:
  port: 8088

application:
  userproperties:
    allowedUsers:
    - '224823566'
    replyForUnknownUser:
      type: 'TEXT'
      text: "tellWhoYouAre"
    incomingRequestChatIdReceiver:
    - '224823566'
  cmdproperties:
    threadsNumber: 4
    queueCapacity: 128
    cmdNameSeparator: " "
    storeCommandsSeconds: 100
    ignoreUnknownCmd: true
    unknownCmdMessageTemplate:
      type: 'TEXT'
      text: "Неизвестная команда!"
    syncReplyMapping:
      start:
        type: 'REPLY_MARKUP'
        text: "Начало работы. Проверьте клавиатуру"
        buttons:
        - text: "home"
        resize: 'true'
      home:
        type: 'INLINED_MARKUP'
        text: "Выберите команду. [info] - информация о node, [mode] - выбрать режим отображения секунд, [color] - выбрать режим отображения цвета, [setup] - переключить в режим настройки"
        buttons:
        - text: "info"
          callback: "info"
        - text: "mode"
          callback: "modeCallback"
        - text: "color"
          callback: "colorCallback"
        - text: "setup"
          callback: "setup"
      modeCallback:
        type: 'INLINED_MARKUP'
        text: "Выберите режим отображения секунд"
        buttons:
        - text: "with sec"
          callback: "mode withSeconds"
        - text: "no sec"
          callback: "mode noSeconds"
        - text: "sec on detect"
          callback: "mode secondsOnDetect"
      colorCallback:
        type: 'INLINED_MARKUP'
        text: "Выберите режим отображения цвета"
        buttons:
        - text: "red"
          callback: "color redDragon"
        - text: "blue"
          callback: "color blueLagoon"
        - text: "green"
          callback: "color greenForrest"
        - text: "grey"
          callback: "color fadeToGray"
    asyncCmdProperties:
      globalTimeoutMs: 20000
      globalTimeoutError:
        type: 'TEXT'
        text: "Таймаут операции"
      replyMapping:
        time:
          reply:
            type: 'TEXT'
            text: "Команда time исполнена на клиенте"
          beforeActionReply:
            type: 'INLINED_MARKUP'
            text: "Подтвердите установленное время [ok] или вернитесь к прошлым настройкам [cancel]"
            buttons:
            - text: "ok"
              callback: "ok"
            - text: "cancel"
              callback: "cancel"
          timeoutMs: 20000
          timeoutError:
            type: 'TEXT'
            text: "Таймаут для команды time!"
        setup:
          reply:
            type: 'TEXT'
            text: "Команда setup исполнена на клиенте"
          beforeActionReply:
            type: 'INLINED_MARKUP'
            text: "Установите время командой [time hh:mm:ss] или вернитесь к прошлым настройкам [cancel]"
            buttons:
            - text: "cancel"
              callback: "cancel"
          timeoutMs: 20000
          timeoutError:
            type: 'TEXT'
            text: "Таймаут для команды setup!"
        info:
          reply:
            type: 'TEXT'
            text: "Команда info исполнена на клиенте"
          beforeActionReply:
            type: 'INLINED_MARKUP'
            text: "Вы запросили информацию о node"
            buttons:
            - text: "home"
              callback: "home"
          timeoutMs: 20000
          timeoutError:
            type: 'TEXT'
            text: "Таймаут для команды info!"
        cancel:
          reply:
            type: 'TEXT'
            text: "Команда cancel исполнена на клиенте"
          beforeActionReply:
            type: 'INLINED_MARKUP'
            text: "Вы подали команду от отмене установленных настроек"
            buttons:
            - text: "home"
              callback: "home"
          timeoutMs: 20000
          timeoutError:
            type: 'TEXT'
            text: "Таймаут для команды cancel!"
        ok:
          reply:
            type: 'TEXT'
            text: "Команда ok исполнена на клиенте"
          beforeActionReply:
            type: 'INLINED_MARKUP'
            text: "Вы подали команду на подтверждение установленных настроек"
            buttons:
            - text: "home"
              callback: "home"
          timeoutMs: 20000
          timeoutError:
            type: 'TEXT'
            text: "Таймаут для команды ok!"
        'mode':
          reply:
            type: 'TEXT'
            text: "Команда по изменению режима отображения исполнена на клиенте"
          beforeActionReply:
            type: 'INLINED_MARKUP'
            text: "Вы подали команду на изменение режима отображения"
            buttons:
            - text: "home"
              callback: "home"
          timeoutMs: 20000
          timeoutError:
            type: 'TEXT'
            text: "Таймаут для команды изменения режима!"
        'color':
          reply:
            type: 'TEXT'
            text: "Команда по изменению цвета исполнена на клиенте"
          beforeActionReply:
            type: 'INLINED_MARKUP'
            text: "Вы подали команду на изменение цвета"
            buttons:
            - text: "home"
              callback: "home"
          timeoutMs: 20000
          timeoutError:
            type: 'TEXT'
            text: "Таймаут для команды изменения цвета!"
  botproperties:
    inTestMode: false
    connectionTimeoutMs: 3000
    name: 'ClockMasterPlekhanov_bot'
    token: '1008566497:AAGKEvr6Ky-waIYxtn2c_EjQhQwxWvYtQms'