server:
    port: 8088

application:
    userproperties:
        allowedUsers:
            - '224823566'
        replyForUnknownUser:
          type: 'TEXT'
          messages:
           - message: "Мне запрещено разговаривать с незнакомцами"
        incomingRequestChatIdReceiver:
            - '32234234'
            - '32232112'
    cmdproperties:
        cmdNameSeparator: " "
        storeCommandsSeconds: 100
        ignoreUnknownCmd: true
        unknownCmdMessageTemplate:
          type: 'TEXT'
          messages:
          - message: "Неизвестная команда!"
        syncReplyMapping:
            start:
              type: 'REPLY_MARKUP'
              messages:
                - message: "home"
              resize: 'true'
            home:
              type: 'INLINED_MARKUP'
              messages:
              - message: "info"
                callback: "info_callback"
              - message: "mode"
                callback: "mode_callback"
              - message: "color"
                callback: "color_callback"
              - message: "setup"
                callback: "setup_callback"
            mode_callback:
              type: 'INLINED_MARKUP'
              - message: "with sec"
                callback: "with_sec_callback"
              - message: "no sec"
                callback: "no_sec_callback"
              - message: "sec on detect"
                callback: "sec_on_detect_callback"
            color_callback:
              type: 'INLINED_MARKUP'
              - message: "red"
                callback: "red_callback"
              - message: "blue"
                callback: "blue_callback"
              - message: "green"
                callback: "green_callback"
              - message: "grey"
                callback: "grey_callback"
        asyncCmdProperties:
            globalTimeoutMs: 3000
            globalTimeoutErrorMessage:
              type: 'TEXT'
              messages:
              - message: "Таймаут операции"
            replyMapping:
                time:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда time исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "cancel"
                      callback: "cancel_callback"
                    - message: "ok"
                      callback: "ok_callback"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды time!"
                setup_callback:
                    replyMessage:
                      type: 'TEXT'
                      messages:
                      - message: "Команда setup исполнена на клиенте"
                    beforeActionReplyMessage:
                      type: 'INLINED_MARKUP'
                      messages:
                      - message: "cancel"
                        callback: "cancel_callback"
                    timeoutMs: 5000
                    timeoutErrorMessage:
                      type: 'TEXT'
                      messages:
                      - message: "Таймаут для команды setup!"
                info_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда info исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды info!"
                cancel_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда cancel исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды cancel!"
                ok_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда ok исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды ok!"
                with_sec_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда with_sec исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды with_sec!"
                no_sec_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда no_sec исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды no_sec!"
                sec_on_detect_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда sec_on_detect исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды sec_on_detect!"
                red_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда red исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды red!"
                gray_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда gray исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды gray!"
                green_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда green исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды green!"
                blue_callback:
                  replyMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Команда blue исполнена на клиенте"
                  beforeActionReplyMessage:
                    type: 'INLINED_MARKUP'
                    messages:
                    - message: "home"
                      callback: "home"
                  timeoutMs: 5000
                  timeoutErrorMessage:
                    type: 'TEXT'
                    messages:
                    - message: "Таймаут для команды blue!"
    botproperties:
        connectionTimeoutMs: 3000
        name: 'AlexeyLemberskiy_bot'
        token: '977798690:AAHMv3t-kfQhxM16MpEvdCa39e5NAQgsZB4'